using System.Linq;
using Cysharp.Net.Http;
using Grpc.Net.Client;
using MagicOnion;
using MagicOnion.Unity;
using Newtonsoft.Json;
using Tute.Shared;
using UnityEngine;

namespace Assets.Scripts
{
    using Cysharp.Threading.Tasks;
    using MagicOnion.Client;
    using MessagePack;
    using MessagePack.Resolvers;

    [MagicOnionClientGeneration(typeof(ITestService))]
    partial class MagicOnionGeneratedClientInitializer
    {
#if UNITY_2019_4_OR_NEWER
        [UnityEngine.RuntimeInitializeOnLoadMethod(
            UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad
        )]
#elif NET5_0_OR_GREATER
        [System.Runtime.CompilerServices.ModuleInitializer]
#endif
        static void RegisterResolvers()
        {
            StaticCompositeResolver.Instance.Register(
                // Add: Use MessagePack formatter resolver generated by the source generator.
                MagicOnionGeneratedClientInitializer.Resolver,
                BuiltinResolver.Instance,
                PrimitiveObjectResolver.Instance
            );

            MessagePackSerializer.DefaultOptions =
                MessagePackSerializer.DefaultOptions.WithResolver(StaticCompositeResolver.Instance);
        }
    }

    public class GameController : MonoBehaviour
    {
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
        public static void OnRuntimeInitialize()
        {
            // Initialize gRPC channel provider when the application is loaded.
            GrpcChannelProviderHost.Initialize(
                new DefaultGrpcChannelProvider(
                    () =>
                        new GrpcChannelOptions()
                        {
                            HttpHandler = new YetAnotherHttpHandler() { Http2Only = true, },
                            DisposeHttpClient = true,
                        }
                )
            );
        }

        [SerializeField]
        Card cardPrefab;

        [SerializeField]
        TextAsset cardsData;

        [SerializeField]
        Sprite[] spriteSheet;

        // Start is called once before the first execution of Update after the MonoBehaviour is created
        void Start()
        {
            Server().Forget();
            var data = JsonConvert.DeserializeObject<CardData[]>(cardsData.text);
            foreach (var item in data)
            {
                var card = Instantiate(cardPrefab, transform);
                card.cardType = item.Type switch
                {
                    "Cups" => CardType.Cups,
                    "Coins" => CardType.Coins,
                    "Clubs" => CardType.Clubs,
                    "Swords" => CardType.Swords,
                    _ => throw new System.Exception($"Unknow type {item.Type}")
                };
                card.value = item.Value;
                card.Sprite = spriteSheet.First(sprite => sprite.name == item.SpriteName);
                card.name = item.Name;
            }
        }

        async UniTaskVoid Server()
        {
            // Connect to the server using gRPC channel.
            var channel = GrpcChannelx.ForTarget(new GrpcChannelTarget("localhost", 5000, true));

            // NOTE: If your project targets non-.NET Standard 2.1, use `Grpc.Core.Channel` class instead.
            // var channel = new Channel("localhost", 5001, new SslCredentials());

            // Create a proxy to call the server transparently.
            var serviceClient = MagicOnionClient.Create<ITestService>(channel);
            var result = await serviceClient.SumAsync(1, 2);
            Debug.Log(result);
        }
    }
}
