# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Server
      run: dotnet build --no-restore
    - name: Test Server
      run: dotnet test --no-build --verbosity normal
  build-client:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
     - name: Build Tute
       uses: game-ci/unity-builder@v4
       env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
       with:
        projectPath: ./Tute.Unity
        targetPlatform: Windows
