# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master","dev" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Server
      run: dotnet build --no-restore
    - name: Test Server
      run: dotnet test --no-build --verbosity normal
    - name: Publish build windows
      run: dotnet publish -r win-x64 -c Release --self-contained
    - name: Publish build linux
      run: dotnet publish -r linux-x64 -c Release --self-contained
    - name: Publish build osx
      run: dotnet publish -r osx-x64 -c Release --self-contained
    - uses: actions/upload-artifact@v4
      with:
         name: Tute-server-win64
         path: Tute.Server/bin/Release/net9.0/win-x64/publish
    - uses: actions/upload-artifact@v4
      with:
        name: Tute-server-linux64
        path: Tute.Server/bin/Release/net9.0/linux-x64/publish
    - uses: actions/upload-artifact@v4
      with:
        name: Tute-server-osx64
        path: Tute.Server/bin/Release/net9.0/osx-x64/publish
  build-windows-client:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
     - uses: actions/cache@v4
       with:
          path: Tute.Unity/Library
          key: Library-Tute.Unity-Windows
          restore-keys: |
            Library-Tute.Unity-
            Library-
     - name: Setup .NET
       uses: actions/setup-dotnet@v4
       with:
        dotnet-version: 9.0.x
     - name: Restore tools
       run: dotnet tool restore
     - name: Restore nuget packages
       run: dotnet nugetforunity restore Tute.Unity
     - name: Build Tute windows
       uses: game-ci/unity-builder@v4
       env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
       with:
        projectPath: ./Tute.Unity
        targetPlatform: StandaloneWindows64
        buildName: Tute-Windows
     - name: Upload windows client
       uses: actions/upload-artifact@v4
       with:
          name: Tute-windows
          path: build/StandaloneWindows64
  build-android-client:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
     - uses: actions/cache@v4
       with:
          path: Tute.Unity/Library
          key: Library-Tute.Unity-Android
          restore-keys: |
            Library-Tute.Unity-
            Library-
     - name: Setup .NET
       uses: actions/setup-dotnet@v4
       with:
        dotnet-version: 9.0.x
     - name: Restore tools
       run: dotnet tool restore
     - name: Restore nuget packages
       run: dotnet nugetforunity restore Tute.Unity
     - name: Build Tute Android
       uses: game-ci/unity-builder@v4
       env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
       with:
        projectPath: ./Tute.Unity
        targetPlatform: Android
        buildName: Tute-Android
     - name: Upload android client
       uses: actions/upload-artifact@v4
       with:
          name: Tute-android
          path: build/Android
